apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-registry
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service  | quote }}
type: kubernetes.io/dockercfg
data:
  .dockercfg: {{ .Values.dockercfg | quote }}
