version: '1.0'

stages:
- stage_1
- stage_2

steps:

  print_env:
    image: alpine:3.8
    stage: stage_2
    commands:
    - env
    
  echo:
    image: alpine:3.8
    stage: stage_1
    commands:
    - echo "hello world"
    
  no_stage:
    image: alpine:3.8
    commands:
    - echo "no stage here"
